#!/bin/bash

osascript -e "tell application \"Spotify\" to activate";
sleep 2

if [[ $(osascript -e 'get volume settings') =~ volume:([0-9]*), ]]; then
	ORIGINAL_VOL="$((${BASH_REMATCH[1]} / 10))"
fi

osascript -e "set Volume 1";
osascript -e "tell application \"Spotify\" to set sound volume to 80";

while [[ $# -gt 1 ]]; do
	if [[ $1 = "-s" ]]; then
		flag="true"
		shift
	elif [[ $1 = "-m" ]]; then
		shift
		osascript -e "tell application \"Spotify\" to set sound volume to $1";
		shift
	fi
done

# echo "$1 $flag";

SPOTIFY_PLAY_URI="";
if [[ "$1" =~ "http" ]]; then
	if [[ "$1" =~ album/([a-zA-Z0-9]*) ]]; then 
        SPOTIFY_PLAY_URI=$( \
            echo "spotify:album:${BASH_REMATCH[1]}" \
        )
	elif [[ "$1" =~ artist/([a-zA-Z0-9]*) ]]; then
		SPOTIFY_PLAY_URI=$( \
            echo "spotify:artist:${BASH_REMATCH[1]}" \
        )
	elif [[ "$1" =~ user/([a-zA-Z0-9]*)/playlist/([a-zA-Z0-9]*) ]]; then
		SPOTIFY_PLAY_URI=$( \
            echo "spotify:user:${BASH_REMATCH[1]}:playlist:${BASH_REMATCH[2]}" \
        )
    fi
else
	if [[ "$1" =~ spotify:(album|user|artist) ]]; then
		SPOTIFY_PLAY_URI=$1;
	fi
fi

# echo $SPOTIFY_PLAY_URI;

if [ "$SPOTIFY_PLAY_URI" != "" ]; then
	osascript -e "tell application \"Spotify\" to play track \"$SPOTIFY_PLAY_URI\"";
	if [[ "$flag" = "true" ]]; then
		# echo "1"
		for (( i = 1; i < 10; i++ )); do
			osascript -e "set Volume $i"
			sleep 3
			#statements
		done
	else
		# echo "2"
		osascript -e "set Volume 100"
	fi
else
	osascript -e "set Volume $ORIGINAL_VOL"
	echo "Error: Please enter Spotift URL";
fi


# spotify:user:spotifytaiwan:playlist:47baPUxFPZOL3WtwD5iFJz
# spotify:album:7GG1AS1p66PcKMIK3uNQqg
# https://open.spotify.com/album/7GG1AS1p66PcKMIK3uNQqg